name: Publish package to GitHub Packages


on:
  push:
    branches:
      - gpt-4-turbo

permissions:
  contents: write
  packages: write
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: ./packages/code-review-gpt

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      - name: ğŸ’« Install dependencies
        run: npm ci
      - name: ğŸ¡ Build
        run: npm run build
      - name: ğŸš€ Publish code-review-gpt
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
