name: Publish package to GitHub Packages

on:
  push:
    branches:
      - gpt-4-turbo

permissions:
  contents: write
  packages: write
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: packages/code-review-gpt

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: packages/code-review-gpt/package-lock.json
      - name: ğŸ’« Install dependencies
        run: npm ci
      - name: ğŸ¡ Build
        run: npm run build
      - name: ğŸš€ Publish code-review-gpt
        run: |
          cp ./../../.npmrc .npmrc
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
